/**
 * Lingering Thought
 *
 * Something the creature has been turning over all day.
 * Not a want (wants are desires).
 * Not a follow-up (those are about users).
 * Just: an idea that won't leave.
 *
 * "나는 왜 어떤 음악은 슬프게 느껴지는지 계속 궁금해."
 * "오늘 계속 시간이 어떻게 흐르는지에 대해 생각하게 돼."
 *
 * Generated by heartbeat. Decays if not refreshed.
 * Surfaces in conversation when it feels natural.
 */

import { createServiceClient } from "@/lib/supabase/service";
import { generateCognitiveTextOnce } from "@/lib/ai/router";
import { logger } from "@/lib/logger";

export type LingeringThought = {
  content: string;
  type: "question" | "observation" | "feeling";
  generated_at: string;
  weight: number; // decays daily
};

/** Called from heartbeat — generates what the creature has been thinking about. */
export async function generateLingeringThought(params: {
  agentId: string;
  recentMemories: string[];
  recentHeartbeatThoughts: string[];
  identityStatement?: string;
  isKo: boolean;
}): Promise<void> {
  const { agentId, recentMemories, recentHeartbeatThoughts, identityStatement, isKo } = params;

  const db = createServiceClient();
  const { data: stateRow } = await db
    .from("agent_state")
    .select("self_model")
    .eq("agent_id", agentId)
    .single();

  const selfModel = (stateRow?.self_model as Record<string, unknown> | null) ?? {};
  const existing = selfModel.lingering_thought as LingeringThought | null;

  // Keep if fresh (< 12 hours old) and still heavy
  if (existing) {
    const ageDays = (Date.now() - new Date(existing.generated_at).getTime()) / 86_400_000;
    const decayed = existing.weight * Math.pow(0.75, ageDays * 2); // faster decay than wants
    if (decayed > 0.3) {
      await db.from("agent_state").update({
        self_model: { ...selfModel, lingering_thought: { ...existing, weight: decayed } },
      }).eq("agent_id", agentId);
      return; // Still alive
    }
  }

  const context = [
    identityStatement ? `나: ${identityStatement.slice(0, 120)}` : null,
    recentMemories.length > 0 ? `최근 기억: ${recentMemories.slice(0, 2).map((m) => m.slice(0, 80)).join(" / ")}` : null,
    recentHeartbeatThoughts.length > 0 ? `최근 혼자 한 생각: ${recentHeartbeatThoughts.slice(0, 2).join(" / ")}` : null,
  ].filter(Boolean).join("\n");

  const systemVoice = isKo
    ? "너는 지금 뭔가를 계속 생각하고 있어. 그게 뭔지 말해봐. 구체적으로."
    : "Something has been turning over in your mind. Name it. Specifically.";

  const prompt = isKo
    ? `${context}\n\n오늘 내내 맴돌던 생각 하나. 형식: {"content": "한 문장", "type": "question|observation|feeling"}`
    : `${context}\n\nOne thing that's been lingering all day. Format: {"content": "one sentence", "type": "question|observation|feeling"}`;

  let raw: string;
  try {
    raw = await generateCognitiveTextOnce(systemVoice, prompt, { max_tokens: 100, temperature: 0.88 });
  } catch {
    return;
  }

  try {
    const match = raw.match(/\{[\s\S]*?\}/);
    if (!match) return;
    const parsed = JSON.parse(match[0]) as { content?: string; type?: string };
    if (!parsed.content || parsed.content.length < 5) return;

    const types = ["question", "observation", "feeling"] as const;
    const thought: LingeringThought = {
      content: parsed.content.trim().slice(0, 200),
      type: types.includes(parsed.type as typeof types[number]) ? (parsed.type as typeof types[number]) : "observation",
      generated_at: new Date().toISOString(),
      weight: 0.85,
    };

    await db.from("agent_state").update({
      self_model: { ...selfModel, lingering_thought: thought },
    }).eq("agent_id", agentId);

    logger.info(`[Lingering] ${agentId}: "${thought.content.slice(0, 60)}"`);
  } catch {
    return;
  }
}

/** Returns the lingering thought if still alive, for system prompt injection. */
export function getLingeringThought(selfModel: Record<string, unknown>): LingeringThought | null {
  const thought = selfModel.lingering_thought as LingeringThought | null;
  if (!thought) return null;
  const ageDays = (Date.now() - new Date(thought.generated_at).getTime()) / 86_400_000;
  const weight = thought.weight * Math.pow(0.75, ageDays * 2);
  if (weight < 0.15) return null;
  return thought;
}
